### ISSUE TITLE
Error: Could not find the include file ".partials/messages"

### ISSUE THREAD

**Issue by ystanev** [ystanev/node_passport_login#1]
Error: Could not find the include file __".partials/messages"__
```
    at getIncludePath (C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:162:13)
    at includeSource (C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:306:17)
    at C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:702:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:678:15)
    at Template.compile (C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:557:12)
    at Object.compile (C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:389:16)
    at handleCache (C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:212:18)
    at tryHandleCache (C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:251:16)
    at View.exports.renderFile [as engine] (C:\projects\node_passport_login\node_modules\ejs\lib\ejs.js:482:10)
    at View.render (C:\projects\node_passport_login\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\projects\node_passport_login\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\projects\node_passport_login\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\projects\node_passport_login\node_modules\express\lib\response.js:1008:7)
    at ServerResponse.res.render (C:\projects\node_passport_login\node_modules\express-ejs-layouts\lib\express-layouts.js:77:18)
    at router.get (C:\projects\node_passport_login\routes\users.js:8:43)
```

**Comment by skeddles** [comment]
whats the solution?

**Comment by TommyQC** [comment]
??? how can i fix it?

**Comment by skeddles** [comment]
give up and just build your own passport implementation, this project hasn't been touched in years
